name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  s3build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: ['22.x']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: 'us-east-1' # リージョンを指定
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # 作成した IAM ロールの ARN

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      - name: Build static site
        run: npm run build

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build/client/ ${{ secrets.S3_BUCKET }} --delete